### ISSUE TITLE
Chromium not storing Google Session

### ISSUE THREAD

**Issue by kladskjasd** [GTANAdam/GDIChromium#13]
Hi, 

First off, I wanted to thank you for the work in this browser. Works like a treat, and it's amazing to have decent font rendering in windows. I formatted my pc and now I am facing a problem with Google / Gmail sessions. I have installed the latest release of GDI Chromium, and no matter how many times I log into Gmail or any Google Service, Chromium will log me out whenever I close the program an restart it again.

This only happens with Google services, as I am able to load other websites that do keep me logged in. Is this a problem of my computer, or might it be something with the latest release? Thanks a lot.

**Comment by GTANAdam** [comment]
Greetings kladskjasd,

The reason you are having issues with Google services is due to the missing API keys in the browser. I want to assure you that I am quite aware of the browser's behavior but not considering investing time into investigating workarounds other than actually requesting API keys from Google Services. Currently, I can recommend using Dashlane or any other password manager that would ease up the sign in process.

If you have the time and knowledge, you are welcome to submit fixes via pull requests.
Thank you!

**Comment by kladskjasd** [comment]
Hi Adam, 

Thanks for taking the time to answer. I was aware of the missing API keys, since Google decided that only Chrome will be able to sync, but I thought that only affected syncing the whole browser with Google, rather than also affecting the saved Gmail session (which I thought was done through cookies only). I won't be able to help since I don't have the expertise, sadly. As you suggested, I'll just keep using Bitwarden to make it easier to log in. Thanks again for your work!

**Comment by kladskjasd** [comment]
Hi again! 

Happy to report I found I solution for this (I REALLY like this browser and was annoyed at not being able to store the session). Apparently it's as easy as disabling this option: 

![image](https://user-images.githubusercontent.com/96435418/149921120-068e93a6-341f-44c8-a8e2-a68c9c79119f.png)

Once the toggle is off, Chromium will save the gmail session with no issues.

**Comment by GTANAdam** [comment]
Nice find! I'll see if I can turn it programmatically on by default!
