### ISSUE TITLE
GDIChromium v.01 - when?!

### ISSUE THREAD

**Issue by Rusenche** [GTANAdam/GDIChromium#3]
When will you release the first version of GDIChromium?! It's been ~ 12 months since you announced on the website https://www.centbrowser.net/en/showthread.php?tid=3555&pid=17112&highlight=GDIChromium#pid17112

**Comment by GTANAdam** [comment]
Greetings @Rusenche,

I understand your frustration towards CentBrowser which I assume is due to their release schedule but, I would like to inform you that this is a project I work on solely in my free time, therefore, I am not obligated to any release schedule. unless there's a bigger community interest, expect no release schedule or any activity any time soon. 

My apologies and thank you for reaching out.
